on:
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  code-scan:
    uses: smallstep/workflows/.github/workflows/code-scan.yml@main
    secrets:
      GITLEAKS_LICENSE_KEY: ${{ secrets.GITLEAKS_LICENSE_KEY }}
